import {test,after,before} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {migrate} from '../src/migrate.mjs';
import {createApp} from '../src/app.mjs';
const db=new PGlite();
// Same SQL and API handlers as production; only identity and transport are fixtures.
const pool={query:(sql,args)=>args?db.query(sql,args):db.exec(sql).then(results=>results.at(-1)),connect:async()=>({query:pool.query,release(){}})};
const users={alice:{id:'10000000-0000-4000-8000-000000000001',email_confirmed_at:'2026-01-01'},bob:{id:'10000000-0000-4000-8000-000000000002',email_confirmed_at:'2026-01-01'},staff:{id:'10000000-0000-4000-8000-000000000003',email_confirmed_at:'2026-01-01'}};
let server,base;
before(async()=>{await migrate(pool);await migrate(pool);const app=createApp({pool,origin:'http://localhost:3100',authenticate:async token=>users[token],staffAccess:async token=>token==='staff'});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/api`;});
after(async()=>{await new Promise(r=>server.close(r));await db.close();});
async function request(path,user='alice',method='GET',body){const r=await fetch(base+path,{method,headers:{Authorization:`Bearer ${user}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
let first,second;
test('requires a verified identity and rejects untrusted origins',async()=>{assert.equal((await request('/projects','invalid')).status,401);assert.equal((await fetch(base+'/projects')).status,401);assert.equal((await fetch(base+'/projects',{headers:{Origin:'https://untrusted.invalid'}})).status,403);});
test('creates multiple isolated projects and retries idempotently',async()=>{const body={id:randomUUID(),address:'100 Test Street',city:'Montréal',plan:'without'};first=(await request('/projects','alice','POST',body)).data;assert.equal(first.id,body.id);assert.equal((await request('/projects','alice','POST',body)).data.id,first.id);second=(await request('/projects','alice','POST',{...body,id:randomUUID(),address:'200 Test Street'})).data;assert.equal((await request('/projects')).data.length,2);assert.equal((await request('/projects','bob')).data.length,0);assert.equal((await request(`/projects/${first.id}`,'bob')).status,404);assert.equal((await request('/projects','bob','POST',body)).status,404);});
test('revision checks prevent lost updates and reject invalid dates',async()=>{const body={revision:first.revision,plan:'with',form:{address:'100 Test Street',city:'Montréal'},services:[],completed:false,visits:[]};let r=await request(`/projects/${first.id}`,'alice','PUT',body);assert.equal(r.status,200);first=r.data;assert.equal((await request(`/projects/${first.id}`,'alice','PUT',body)).status,409);assert.equal((await request(`/projects/${first.id}`,'alice','PUT',{...body,revision:first.revision,visits:[{name:'Visitor',date:'2026-02-31',time:'10:30'}]})).status,400);assert.equal((await request(`/projects/${second.id}`)).data.revision,0);});
test('photo bytes are stored atomically, scoped to project and invalidate review',async()=>{const input={id:randomUUID(),kind:'photo',name:'sample.png',mime_type:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+afoQAAAAASUVORK5CYII='};const r=await request(`/projects/${first.id}/files`,'alice','POST',input);assert.equal(r.status,201);const files=(await request(`/projects/${first.id}/files`)).data;assert.equal(files.length,1);assert.equal((await request(`/projects/${second.id}/files`)).data.length,0);assert.equal((await request(`/projects/${first.id}/files`,'bob')).status,404);const path=`/projects/${first.id}/files/${input.id}/content`;assert.equal((await request(path,'bob')).status,404);const content=await fetch(base+path,{headers:{Authorization:'Bearer alice'}});assert.equal(content.status,200);assert.deepEqual(Buffer.from(await content.arrayBuffer()),Buffer.from(input.data,'base64'));assert.equal((await request(`/projects/${first.id}/files`,'alice','POST',{...input,id:randomUUID(),data:Buffer.from('<script>bad</script>').toString('base64')})).status,400);first=(await request(`/projects/${first.id}`)).data;});
test('submission and staff review enforce completeness and staff access',async()=>{assert.equal((await request(`/projects/${first.id}/submit`,'alice','POST',{revision:first.revision})).status,400);const form={address:'100 Test Street',city:'Montréal',postal:'H2X 1Y4',type:'0',price:'500000',broker:'0',timeline:'0',name:'Test Seller',email:'seller@example.test',phone:'5145550100',date:'',time:'0',language:'fr',notes:'',consent:true};first=(await request(`/projects/${first.id}`,'alice','PUT',{revision:first.revision,plan:'with',form,services:[],completed:true,visits:[]})).data;first=(await request(`/projects/${first.id}/submit`,'alice','POST',{revision:first.revision})).data;assert.equal(first.status,'submitted');assert.equal((await request('/admin/projects')).status,403);assert.equal((await request('/admin/projects','staff')).data.length,1);const r=await request(`/admin/projects/${first.id}/review`,'staff','POST',{revision:first.revision,decision:'approved',note:''});assert.equal(r.status,200);assert.equal(r.data.status,'approved');assert.ok((await request('/admin/audit','staff')).data.length>=3);});
