export class ApiError extends Error{constructor(status,message){super(message);this.status=status;}}
export const uuid=value=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const metadata='id,project_id,owner_id,kind,name,size,mime_type,storage_path';
export function repository(pool){
 async function transaction(work){const db=await pool.connect();try{await db.query('begin');const result=await work(db);await db.query('commit');return result;}catch(error){await db.query('rollback');throw error;}finally{db.release();}}
 async function owned(db,user,id,lock=false){if(!uuid(id))throw new ApiError(404,'NOT_FOUND');const {rows}=await db.query(`select * from workspace.projects where id=$1 and owner_id=$2${lock?' for update':''}`,[id,user]);if(!rows[0])throw new ApiError(404,'NOT_FOUND');return rows[0];}
 async function touch(db,id){await db.query("update workspace.projects set revision=revision+1,status='draft',review_note='',updated_at=now() where id=$1",[id]);}
 function checkRevision(row,value){if(!Number.isInteger(value)||row.revision!==value)throw new ApiError(409,'REVISION_CONFLICT');}
 async function audit(db,user,id,action,meta={}){await db.query('insert into workspace.audit_events(actor_id,project_id,action,metadata) values($1,$2,$3,$4)',[user,id,action,JSON.stringify(meta)]);}
 return {
  async list(user){return (await pool.query('select * from workspace.projects where owner_id=$1 order by updated_at desc,id limit 100',[user])).rows;},
  get:(user,id)=>owned(pool,user,id),
  async create(user,input){if(!input||!uuid(input.id)||typeof input.address!=='string'||input.address.trim().length<3||typeof input.city!=='string'||input.city.trim().length<2)throw new ApiError(400,'VALIDATION');return transaction(async db=>{
   await db.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[user]);
   const existing=await db.query('select * from workspace.projects where id=$1',[input.id]);if(existing.rows[0]){if(existing.rows[0].owner_id!==user)throw new ApiError(404,'NOT_FOUND');return existing.rows[0];}
   if(Number((await db.query('select count(*) as count from workspace.projects where owner_id=$1',[user])).rows[0].count)>=100)throw new ApiError(400,'PROJECT_LIMIT');
   const details={address:input.address.trim(),city:input.city.trim()};await db.query('select workspace_private.validate_project_input($1,$2,$3,$4)',[input.plan,JSON.stringify(details),[],'[]']);
   const row=(await db.query('insert into workspace.projects(id,owner_id,plan,details) values($1,$2,$3,$4) returning *',[input.id,user,input.plan,JSON.stringify(details)])).rows[0];await audit(db,user,row.id,'project.created');return row;
  });},
  async save(user,id,input){return transaction(async db=>{const row=await owned(db,user,id,true);checkRevision(row,input?.revision);if(typeof input.completed!=='boolean')throw new ApiError(400,'VALIDATION');await db.query('select workspace_private.validate_project_input($1,$2,$3,$4)',[input.plan,JSON.stringify(input.form),input.services,JSON.stringify(input.visits)]);
   return (await db.query("update workspace.projects set plan=$1,details=$2,services=$3,completed=$4,visits=$5,revision=revision+1,status='draft',review_note='',updated_at=now() where id=$6 returning *",[input.plan,JSON.stringify(input.form),input.services,input.completed,JSON.stringify(input.visits),id])).rows[0];});},
  async submit(user,id,input){return transaction(async db=>{const row=await owned(db,user,id,true);checkRevision(row,input?.revision);if(!['draft','changes_requested'].includes(row.status))throw new ApiError(400,'VALIDATION');await db.query('select workspace_private.validate_submission(p) from workspace.projects p where id=$1',[id]);await audit(db,user,id,'project.submitted');return (await db.query("update workspace.projects set status='submitted',revision=revision+1,updated_at=now() where id=$1 returning *",[id])).rows[0];});},
  async files(user,id){await owned(pool,user,id);return (await pool.query(`select ${metadata} from workspace.files where project_id=$1 order by created_at,id`,[id])).rows;},
  async content(user,id,fileId){await owned(pool,user,id);if(!uuid(fileId))throw new ApiError(404,'NOT_FOUND');const row=(await pool.query('select name,mime_type,content from workspace.files where project_id=$1 and id=$2',[id,fileId])).rows[0];if(!row)throw new ApiError(404,'NOT_FOUND');return row;},
  async upload(user,id,input){if(!input||!uuid(input.id)||!['photo','document'].includes(input.kind)||typeof input.name!=='string'||!input.name.length||input.name.length>255||/[\x00-\x1f]/.test(input.name)||typeof input.data!=='string'||input.data.length>13981016||!/^[A-Za-z0-9+/]+={0,2}$/.test(input.data))throw new ApiError(400,'FILE_LIMIT');
   const data=Buffer.from(input.data,'base64');const signatures={'image/jpeg':()=>data[0]===255&&data[1]===216&&data[2]===255,'image/png':()=>data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),'image/webp':()=>data.toString('ascii',0,4)==='RIFF'&&data.toString('ascii',8,12)==='WEBP','application/pdf':()=>data.toString('ascii',0,5)==='%PDF-'};
   if(data.length<12||data.length>10485760||!signatures[input.mime_type]?.()||(input.kind==='photo'&&input.mime_type==='application/pdf'))throw new ApiError(400,'FILE_LIMIT');
   return transaction(async db=>{await owned(db,user,id,true);const existing=(await db.query('select id from workspace.files where id=$1',[input.id])).rows[0];if(existing)throw new ApiError(409,'FILE_CONFLICT');const count=Number((await db.query('select count(*) as count from workspace.files where project_id=$1 and kind=$2',[id,input.kind])).rows[0].count);if(count>=(input.kind==='photo'?8:10))throw new ApiError(400,'FILE_LIMIT');
    const row=(await db.query(`insert into workspace.files(id,project_id,owner_id,kind,name,size,mime_type,content) values($1,$2,$3,$4,$5,$6,$7,$8) returning ${metadata}`,[input.id,id,user,input.kind,input.name,data.length,input.mime_type,data])).rows[0];await touch(db,id);await audit(db,user,id,'file.uploaded',{id:row.id});return row;});},
  async remove(user,id,fileId){return transaction(async db=>{await owned(db,user,id,true);if(!uuid(fileId))throw new ApiError(404,'NOT_FOUND');const deleted=await db.query('delete from workspace.files where project_id=$1 and id=$2 returning id',[id,fileId]);if(!deleted.rows[0])throw new ApiError(404,'NOT_FOUND');await touch(db,id);await audit(db,user,id,'file.removed',{id:fileId});return {ok:true};});},
  async reviewQueue(){return (await pool.query("select * from workspace.projects where status='submitted' order by updated_at limit 100")).rows;},
  async auditLog(){return (await pool.query('select * from workspace.audit_events order by created_at desc limit 50')).rows;},
  async adminFiles(id){if(!uuid(id))throw new ApiError(404,'NOT_FOUND');return (await pool.query(`select ${metadata} from workspace.files where project_id=$1`,[id])).rows;},
  async adminContent(id,fileId){if(!uuid(id)||!uuid(fileId))throw new ApiError(404,'NOT_FOUND');const row=(await pool.query('select name,mime_type,content from workspace.files where project_id=$1 and id=$2',[id,fileId])).rows[0];if(!row)throw new ApiError(404,'NOT_FOUND');return row;},
  async review(user,id,input){if(!uuid(id)||!['approved','changes_requested'].includes(input?.decision)||typeof input.note!=='string'||input.note.length>2000||(input.decision==='changes_requested'&&!input.note.trim()))throw new ApiError(400,'VALIDATION');return transaction(async db=>{const row=(await db.query('select * from workspace.projects where id=$1 for update',[id])).rows[0];if(!row)throw new ApiError(404,'NOT_FOUND');checkRevision(row,input.revision);if(row.status!=='submitted')throw new ApiError(409,'REVISION_CONFLICT');if(input.decision==='approved')await db.query('select workspace_private.validate_submission(p) from workspace.projects p where id=$1',[id]);await audit(db,user,id,'project.reviewed',{decision:input.decision});return (await db.query('update workspace.projects set status=$1,review_note=$2,revision=revision+1,updated_at=now() where id=$3 returning *',[input.decision,input.note,id])).rows[0];});}
 };
}

