import {useEffect,useState,type FormEvent} from 'react';
import {ArrowRight,BadgeCheck,Building2,ExternalLink,Mail,Phone,ShieldCheck,UserRoundCheck} from 'lucide-react';
import type {Language} from './seller-copy';
import {useAuth} from './auth';
import {supabase} from './lib/supabase';
import './brokers.css';

type Profile={application_id:string;full_name:string;license_number:string;agency_name:string;contact_email:string;contact_phone:string;bio:string;verified_at:string};
type Application=Profile&{status:'pending'|'verified'|'changes_requested';revision:number;review_note:string;public_consent:boolean};
const copy={
  fr:{title:'Courtiers vérifiés',intro:'Consultez les profils des courtiers dont le permis OACIQ a été vérifié.',apply:'Faire vérifier mon permis',applyText:'Soumettez votre nom, votre numéro de permis et votre agence. Un administrateur vérifiera votre inscription au registre de l’OACIQ.',login:'Connectez-vous pour demander une vérification.',empty:'Aucun courtier vérifié pour le moment.',loading:'Chargement…',refresh:'Actualiser',error:'Impossible de charger les profils. Réessayez.',formTitle:'Demande de vérification',name:'Nom professionnel',license:'Numéro de permis OACIQ',agency:'Agence immobilière',email:'Courriel professionnel public',phone:'Téléphone professionnel public',bio:'Présentation (facultatif)',consent:'J’accepte de rendre publics mon nom, mon numéro de permis, mon agence, mes coordonnées professionnelles et ma présentation après vérification.',submit:'Soumettre à la vérification',save:'Enregistrer et renvoyer',statusPending:'En attente de vérification',statusVerified:'Permis vérifié',statusChanges:'Modifications demandées',reviewNote:'Note de l’équipe',success:'Demande envoyée. Votre profil sera public après vérification.',formError:'Vérifiez les champs et acceptez la publication de votre profil après vérification.',directory:'Consulter le registre OACIQ',profile:'Profil professionnel',contact:'Contacter',notConfigured:'Le service de vérification n’est pas configuré.',verifyNote:'Confirmez dans le registre OACIQ le nom, le permis valide et le rattachement à l’agence. Inscrivez le résultat de la vérification dans la note.'},
  en:{title:'Verified brokers',intro:'Find brokers whose OACIQ licence has been checked.',apply:'Verify my licence',applyText:'Submit your name, licence number and agency. An administrator will check your entry in the OACIQ register.',login:'Sign in to request verification.',empty:'No verified brokers yet.',loading:'Loading…',refresh:'Refresh',error:'Profiles could not be loaded. Please retry.',formTitle:'Verification request',name:'Professional name',license:'OACIQ licence number',agency:'Real estate agency',email:'Public business email',phone:'Public business phone',bio:'Introduction (optional)',consent:'I agree to publish my name, licence number, agency, business contact details and introduction after verification.',submit:'Submit for verification',save:'Save and resubmit',statusPending:'Awaiting verification',statusVerified:'Licence verified',statusChanges:'Changes requested',reviewNote:'Team note',success:'Request sent. Your profile will be public after verification.',formError:'Check the fields and consent to publishing your profile after verification.',directory:'Check the OACIQ register',profile:'Professional profile',contact:'Contact',notConfigured:'The verification service is not configured.',verifyNote:'Confirm the name, active licence and agency affiliation in the OACIQ register. Record the result in the review note.'},
  zh:{title:'已认证经纪',intro:'查看已由管理员核验 OACIQ 执照的经纪资料。',apply:'申请经纪认证',applyText:'填写姓名、执照号码和所属机构。管理员会在 OACIQ 官方登记册中人工核对。',login:'登录后可提交经纪认证申请。',empty:'目前还没有通过认证的经纪。',loading:'正在加载…',refresh:'刷新',error:'无法加载经纪资料，请重试。',formTitle:'经纪认证申请',name:'经纪姓名',license:'OACIQ 执照号码',agency:'所属房地产机构',email:'公开的工作邮箱',phone:'公开的工作电话',bio:'个人介绍（选填）',consent:'我同意认证通过后公开姓名、执照号码、所属机构、工作联系方式和个人介绍。',submit:'提交认证',save:'保存并重新提交',statusPending:'等待管理员核验',statusVerified:'执照已认证',statusChanges:'管理员要求修改',reviewNote:'管理员说明',success:'申请已提交。管理员核验通过后，您的资料才会公开。',formError:'请检查表单，并确认同意认证通过后公开资料。',directory:'查看 OACIQ 官方登记册',profile:'经纪资料',contact:'联系经纪',notConfigured:'认证服务尚未配置。',verifyNote:'请在 OACIQ 登记册确认姓名、执照有效状态和所属机构，并在核验说明中记录结果。'}
};

const emptyForm={full_name:'',license_number:'',agency_name:'',contact_email:'',contact_phone:'',bio:'',public_consent:false};
export function BrokersPage({lang}:{lang:Language}){
  const c=copy[lang],{user}=useAuth();
  const [profiles,setProfiles]=useState<Profile[]>([]),[mine,setMine]=useState<Application|null>(null),[form,setForm]=useState(emptyForm),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function refresh(){
    if(!supabase){setLoading(false);setError(c.notConfigured);return;}
    setLoading(true);setError('');
    const [publicResult,ownResult]=await Promise.all([
      supabase.rpc('get_verified_brokers'),
      user?supabase.from('broker_applications').select('*').eq('user_id',user.id).maybeSingle():Promise.resolve({data:null,error:null} as any),
    ]);
    setLoading(false);
    if(publicResult.error||ownResult.error){setError(c.error);return;}
    const list=(publicResult.data||[]) as Profile[];setProfiles(list);
    const own=ownResult.data as Application|null;setMine(own);
    if(own)setForm({full_name:own.full_name,license_number:own.license_number,agency_name:own.agency_name,contact_email:own.contact_email,contact_phone:own.contact_phone,bio:own.bio,public_consent:own.public_consent});
    else if(user?.email)setForm(p=>({...p,contact_email:user.email||''}));
  }
  useEffect(()=>{void refresh();},[user?.id,lang]);
  function value(key:keyof typeof emptyForm,value:string|boolean){setForm(p=>({...p,[key]:value}));}
  async function submit(e:FormEvent){e.preventDefault();if(!supabase||!user||busy)return;setBusy(true);setError('');setMessage('');
    const {error:saveError}=await supabase.rpc('submit_broker_application',{p_full_name:form.full_name,p_license_number:form.license_number,p_agency_name:form.agency_name,p_contact_email:form.contact_email,p_contact_phone:form.contact_phone,p_bio:form.bio,p_public_consent:form.public_consent});
    setBusy(false);if(saveError){setError(c.formError);return;}setMessage(c.success);await refresh();
  }
  return <main className="brokers-page"><div className="brokers-heading"><span className="eyebrow"><ShieldCheck/>{c.profile}</span><h1>{c.title}</h1><p>{c.intro}</p></div>
    {error&&<p className="brokers-alert" role="alert">{error}</p>}{message&&<p className="brokers-success" role="status">{message}</p>}
    {loading?<p role="status">{c.loading}</p>:profiles.length?<section className="broker-directory" aria-label={c.title}>{profiles.map(p=><article className="broker-profile" key={p.application_id}><span className="broker-badge"><BadgeCheck/>{c.statusVerified}</span><h2>{p.full_name}</h2><p className="broker-agency"><Building2/>{p.agency_name}</p><p className="broker-license">OACIQ · {p.license_number}</p>{p.bio&&<p className="broker-bio">{p.bio}</p>}<div className="broker-contact">{p.contact_email&&<a href={`mailto:${encodeURIComponent(p.contact_email)}`}><Mail/>{c.contact}</a>}{p.contact_phone&&<a href={`tel:${encodeURIComponent(p.contact_phone.replace(/[^+0-9]/g,''))}`}><Phone/>{p.contact_phone}</a>}</div></article>)}</section>:<p className="brokers-empty">{c.empty}</p>}
    <a className="broker-register-link" href="https://registre.oaciq.com/en/find-broker" target="_blank" rel="noreferrer">{c.directory}<ExternalLink/></a>
    <section className="broker-apply"><div><span className="broker-apply-icon"><UserRoundCheck/></span><h2>{c.apply}</h2><p>{c.applyText}</p></div>
      {!user?<div className="broker-login"><p>{c.login}</p><a href="#login">{lang==='zh'?'登录':lang==='fr'?'Se connecter':'Sign in'}<ArrowRight/></a></div>:<>
        {mine&&<p className={`broker-status ${mine.status}`} role="status">{mine.status==='verified'?c.statusVerified:mine.status==='changes_requested'?c.statusChanges:c.statusPending}{mine.review_note&&<small>{c.reviewNote}: {mine.review_note}</small>}</p>}
        <form className="broker-form" onSubmit={submit}><h3>{c.formTitle}</h3><label>{c.name} *<input required minLength={2} maxLength={100} autoComplete="name" value={form.full_name} onChange={e=>value('full_name',e.target.value)}/></label><label>{c.license} *<input required minLength={3} maxLength={40} pattern="[A-Za-z0-9 -]+" value={form.license_number} onChange={e=>value('license_number',e.target.value)}/></label><label>{c.agency} *<input required minLength={2} maxLength={150} value={form.agency_name} onChange={e=>value('agency_name',e.target.value)}/></label><div className="broker-contact-fields"><label>{c.email} *<input type="email" required maxLength={254} autoComplete="email" value={form.contact_email} onChange={e=>value('contact_email',e.target.value)}/></label><label>{c.phone}<input type="tel" maxLength={40} autoComplete="tel" value={form.contact_phone} onChange={e=>value('contact_phone',e.target.value)}/></label></div><label>{c.bio}<textarea rows={3} maxLength={500} value={form.bio} onChange={e=>value('bio',e.target.value)}/></label><label className="broker-consent"><input type="checkbox" required checked={form.public_consent} onChange={e=>value('public_consent',e.target.checked)}/>{c.consent}</label><button className="broker-submit" disabled={busy}>{busy?c.loading:mine?c.save:c.submit}<ArrowRight/></button></form>
      </>}
    </section>
  </main>;
}

type ReviewApplication=Omit<Application,'application_id'|'verified_at'>&{id:string;user_id:string;submitted_at:string};
export function BrokerReview({lang}:{lang:Language}){
  const c=copy[lang];const [rows,setRows]=useState<ReviewApplication[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function refresh(){if(!supabase){setLoading(false);setError(c.notConfigured);return;}setLoading(true);const result=await supabase.from('broker_applications').select('id,user_id,full_name,license_number,agency_name,contact_email,contact_phone,bio,public_consent,status,revision,review_note,submitted_at').eq('status','pending').order('submitted_at');setLoading(false);if(result.error){setError(c.error);return;}setRows((result.data||[]) as ReviewApplication[]);}
  useEffect(()=>{void refresh();},[]);
  async function review(row:ReviewApplication,decision:'verified'|'changes_requested'){if(!supabase||busy)return;const note=notes[row.id]||'';if(!note.trim()){setError(lang==='zh'?'请先填写核验说明，再确认执照。':lang==='fr'?'Ajoutez une note de vérification avant de confirmer le permis.':'Add a verification note before confirming the licence.');return;}setBusy(true);setError('');const result=await supabase.rpc('review_broker_application',{p_application_id:row.id,p_expected_revision:row.revision,p_decision:decision,p_note:note.trim()});setBusy(false);if(result.error){setError(c.error);return;}await refresh();}
  return <section className="admin-panel broker-review"><div className="broker-review-heading"><div><h2>{c.title}</h2><p>{c.verifyNote}</p></div><button className="admin-secondary" disabled={loading||busy} onClick={()=>void refresh()}>{c.refresh}</button></div>{error&&<p role="alert">{error}</p>}{loading?<p role="status">{c.loading}</p>:rows.length?rows.map(row=><article key={row.id}><div className="broker-review-title"><div><h3>{row.full_name}</h3><p>{row.agency_name} · OACIQ {row.license_number}</p></div><a href="https://registre.oaciq.com/en/find-broker" target="_blank" rel="noreferrer">{c.directory}<ExternalLink/></a></div><p>{row.contact_email}{row.contact_phone?` · ${row.contact_phone}`:''}</p>{row.bio&&<p>{row.bio}</p>}<label>{copy[lang].reviewNote}<textarea maxLength={2000} value={notes[row.id]??row.review_note} onChange={e=>setNotes(v=>({...v,[row.id]:e.target.value}))}/></label><div className="broker-review-actions"><button disabled={busy} onClick={()=>void review(row,'verified')}>{lang==='zh'?'核验通过':lang==='fr'?'Vérifier le permis':'Verify licence'}<BadgeCheck/></button><button disabled={busy} onClick={()=>void review(row,'changes_requested')}>{lang==='zh'?'退回修改':lang==='fr'?'Demander des corrections':'Request changes'}</button></div></article>):<p>{c.empty}</p>}</section>;
}
