export const sellerCopy = {
  fr: {
    back: "Retour à l’accueil",
    eyebrow: "VENDRE À VOTRE FAÇON",
    title: "Votre propriété. Votre façon de vendre.",
    intro:
      "À Montréal, avancez à votre rythme : vendez vous-même et ajoutez de l’aide au besoin, ou choisissez un courtier.",
    steps: [
      "Votre formule",
      "Votre propriété",
      "Vos coordonnées",
      "Récapitulatif",
    ],
    with: "Avec courtier",
    without: "Sans courtier",
    withTag: "Un professionnel à vos côtés",
    withoutTag: "Vous gardez les commandes",
    withText: "Un courtier vous accompagne de l’évaluation à la signature.",
    withoutText:
      "Vous gérez votre vente et choisissez progressivement les services dont vous avez besoin.",
    withItems: [
      "Évaluation comparative par un courtier",
      "Photographie et mise en marché",
      "Coordination des visites et des offres",
      "Négociation et suivi de la transaction",
    ],
    withoutItems: [
      "Séance photo professionnelle",
      "Vidéo de présentation de la propriété",
      "Analyse de marché par un professionnel qualifié",
      "Conception de la fiche et préparation des informations",
    ],
    agreed: "Honoraires selon le mandat",
    agreedNote:
      "Les services et la commission sont convenus avec votre courtier avant tout engagement.",
    sample: "Prix d’exemple",
    taxes: "CAD + taxes",
    fixed: "Services à la carte • sans achat à cette étape",
    chooseWith: "Choisir un courtier",
    chooseWithout: "Choisir la vente autonome",
    boundary:
      "Le forfait sans courtier ne comprend pas la représentation, les visites ni la négociation. Toute assistance de courtage ferait l’objet d’un accord distinct.",
    demo: "Version de démonstration : aucun paiement, envoi de données ou rendez-vous confirmé.",
    saveNotice: "Votre dossier reste privé. Ce parcours ne commande aucun service, ne confirme aucun rendez-vous et ne publie pas votre propriété.",
    propertyTitle: "Parlons de votre propriété.",
    propertyText:
      "Préparez votre dossier privé. Vous pourrez demander une vérification depuis votre espace vendeur.",
    address: "Adresse de la propriété",
    city: "Ville",
    postal: "Code postal",
    type: "Type de propriété",
    price: "Prix souhaité (CAD, facultatif)",
    types: ["Maison", "Condo", "Plex", "Commercial"],
    broker: "Avez-vous déjà un courtier ?",
    brokerOptions: ["Non", "Oui", "Je préfère en discuter"],
    timeline: "Quand souhaitez-vous vendre ?",
    timelines: [
      "Dès que possible",
      "Dans 1 à 3 mois",
      "Dans 3 à 6 mois",
      "Je me renseigne",
    ],
    photos: "Photos de votre propriété (facultatif)",
    photoHelp:
      "Jusqu’à 8 fichiers JPG, PNG ou WebP, 10 Mo chacun. Stockage privé dans votre compte. Une photo sera nécessaire pour demander une vérification.",
    remove: "Retirer",
    photoError:
      "Choisissez jusqu’à 8 images JPG, PNG ou WebP de 10 Mo maximum chacune.",
    photoPreviewError: "Une photo ne peut pas être affichée. Vérifiez votre connexion et rechargez le dossier pour renouveler les aperçus.",
    next: "Continuer",
    previous: "Retour",
    appointmentTitle: "Comment vous joindre ?",
    appointmentText:
      "Indiquez vos coordonnées. Une disponibilité est facultative : il s’agit d’une préférence, pas d’une réservation.",
    name: "Nom complet",
    email: "Courriel",
    phone: "Téléphone",
    date: "Date souhaitée (facultatif)",
    noAppointment: "Aucune disponibilité indiquée — aucun rendez-vous réservé",
    time: "Moment préféré",
    times: ["Matin", "Après-midi", "Soir"],
    language: "Langue de communication",
    notes: "Précisions (facultatif)",
    consent:
      "J’accepte l’enregistrement de mes informations dans mon compte privé et leur consultation par l’équipe autorisée pour traiter mon dossier. Une vérification ne les rend pas publiques et ne confirme aucun service.",
    review: "Vérifier mes informations",
    reviewTitle: "Tout est prêt pour la prochaine étape.",
    reviewText:
      "Vérifiez vos informations avant d’enregistrer votre dossier et d’ouvrir votre espace vendeur.",
    service: "Votre formule",
    property: "Votre propriété",
    appointment: "Votre disponibilité souhaitée",
    contact: "Vos coordonnées",
    included: "Services à convenir avec votre courtier",
    estimate: "Tarif indicatif",
    noCharge:
      "Aucun montant ne sera débité. Le prix final et les taxes devront être confirmés avant un véritable paiement.",
    finish: "Enregistrer mon dossier",
    doneTitle: "Votre parcours est prêt.",
    doneText:
      "Votre dossier est enregistré dans votre compte privé. Aucun service n’a été commandé, aucun rendez-vous confirmé et aucun paiement effectué.",
    again: "Revenir à l’accueil",
    edit: "Modifier",
    photosCount: "photo(s) enregistrée(s)",
    required: "Les champs marqués * sont obligatoires.",
    invalidDate: "Choisissez une date à partir d’aujourd’hui.",
    invalidPrice: "Indiquez un montant positif.",
    invalidPostal: "Saisissez un code postal canadien valide.",
  },
  en: {
    back: "Back to home",
    eyebrow: "SELL YOUR WAY",
    title: "Your property. Your way to sell.",
    intro:
      "In Montréal, sell at your own pace: start independently and add help as you need it, or choose a broker.",
    steps: ["Your service", "Your property", "Your contact details", "Review"],
    with: "With a broker",
    without: "Without a broker",
    withTag: "A professional by your side",
    withoutTag: "You stay in control",
    withText: "A broker supports you from valuation through signing.",
    withoutText:
      "Manage your sale and add professional help whenever you need it.",
    withItems: [
      "Comparative valuation by a broker",
      "Photography and marketing",
      "Visit and offer coordination",
      "Negotiation and transaction follow-up",
    ],
    withoutItems: [
      "Professional photography session",
      "Property presentation video",
      "Market analysis by a qualified professional",
      "Listing page design and information preparation",
    ],
    agreed: "Fees agreed in the mandate",
    agreedNote:
      "Services and commission are agreed with your broker before any commitment.",
    sample: "Example price",
    taxes: "CAD + taxes",
    fixed: "Optional services • no purchase at this step",
    chooseWith: "Choose broker support",
    chooseWithout: "Choose self-sale",
    boundary:
      "The self-sale package excludes representation, visits and negotiation. Any brokerage assistance would require a separate agreement.",
    demo: "Demo version: no payment, data submission or confirmed appointment.",
    saveNotice: "Your project stays private. This process does not order a service, confirm an appointment or publish your property.",
    propertyTitle: "Tell us about your property.",
    propertyText:
      "Prepare your private project. You can request a review from your seller dashboard.",
    address: "Property address",
    city: "City",
    postal: "Postal code",
    type: "Property type",
    price: "Desired price (CAD, optional)",
    types: ["House", "Condo", "Plex", "Commercial"],
    broker: "Do you already have a broker?",
    brokerOptions: ["No", "Yes", "I would like to discuss it"],
    timeline: "When would you like to sell?",
    timelines: [
      "As soon as possible",
      "In 1–3 months",
      "In 3–6 months",
      "Just exploring",
    ],
    photos: "Property photos (optional)",
    photoHelp:
      "Up to 8 JPG, PNG or WebP files, 10 MB each. Stored privately in your account. At least one photo is needed to request a review.",
    remove: "Remove",
    photoError:
      "Choose up to 8 JPG, PNG or WebP images, no larger than 10 MB each.",
    photoPreviewError: "A photo could not be displayed. Check your connection and reload the project to refresh its previews.",
    next: "Continue",
    previous: "Back",
    appointmentTitle: "How can we reach you?",
    appointmentText:
      "Enter your contact details. You may add your availability, but this is optional and does not create a booking.",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    date: "Preferred date (optional)",
    noAppointment: "No availability provided — no appointment booked",
    time: "Preferred time",
    times: ["Morning", "Afternoon", "Evening"],
    language: "Communication language",
    notes: "Additional details (optional)",
    consent:
      "I agree to save my information in my private account and allow the authorized team to access it to handle my project. A review does not make it public or confirm any service.",
    review: "Review my information",
    reviewTitle: "Ready for the next step.",
    reviewText:
      "Check your information before saving your project and opening your seller dashboard.",
    service: "Your service",
    property: "Your property",
    appointment: "Your preferred availability",
    contact: "Your contact details",
    included: "Services to agree with your broker",
    estimate: "Indicative price",
    noCharge:
      "Nothing will be charged. The final price and taxes must be confirmed before an actual payment.",
    finish: "Save my project",
    doneTitle: "Your plan is ready.",
    doneText:
      "Your project is saved in your private account. No service has been ordered, no appointment confirmed and no payment taken.",
    again: "Back to home",
    edit: "Edit",
    photosCount: "photo(s) saved",
    required: "Fields marked * are required.",
    invalidDate: "Choose today or a future date.",
    invalidPrice: "Enter a positive amount.",
    invalidPostal: "Enter a valid Canadian postal code.",
  },
  zh: {
    back: "返回首页",
    eyebrow: "选择适合您的卖房方式",
    title: "您的房产，由您选择怎样出售。",
    intro:
      "服务蒙特利尔：先自主卖房，再按需要增加专业帮助；也可以选择经纪全程协助。",
    steps: ["选择方案", "房屋资料", "联系方式", "核对信息"],
    with: "有经纪服务",
    without: "无经纪自售",
    withTag: "专业经纪全程协助",
    withoutTag: "卖房节奏由您掌握",
    withText: "从房产评估到签字完成，由经纪陪您处理每个环节。",
    withoutText: "先自主推进卖房，再按需要选择摄影、视频、市场分析或咨询。",
    withItems: [
      "经纪提供同类房产对比评估",
      "专业摄影与上市推广",
      "协调看房和管理报价",
      "谈判协助与交易跟进",
    ],
    withoutItems: [
      "专业人员上门拍摄房屋照片",
      "房屋展示视频",
      "由合资格专业人士提供市场分析",
      "房源页面设计与资料整理",
    ],
    agreed: "费用按经纪协议确定",
    agreedNote: "签约前与经纪确认服务范围及佣金，不在此页面收取费用。",
    sample: "示例价格",
    taxes: "加元 + 税",
    fixed: "按需选择服务 · 此步骤无需购买",
    chooseWith: "选择经纪服务",
    chooseWithout: "选择自主出售",
    boundary:
      "自售套餐不包含经纪代理、带看或谈判。若需经纪协助，须另行确认服务及协议。",
    demo: "当前为演示版：不会扣款、发送个人资料或确认预约。",
    saveNotice: "您的项目保存在私有账号中。填写此流程不会下单、确认预约或公开房源。",
    propertyTitle: "先了解一下您的房屋。",
    propertyText: "先整理您的私有房屋资料，之后可以在工作台申请审核。",
    address: "房屋地址",
    city: "城市",
    postal: "邮政编码",
    type: "房产类型",
    price: "期望售价（加元，选填）",
    types: ["独立屋 / House", "公寓 / Condo", "多户住宅 / Plex", "商业物业"],
    broker: "您目前是否已有经纪？",
    brokerOptions: ["没有", "有", "希望进一步沟通"],
    timeline: "希望什么时候出售？",
    timelines: ["尽快出售", "1–3 个月内", "3–6 个月内", "先了解一下"],
    photos: "房屋照片（选填）",
    photoHelp: "最多 8 张 JPG、PNG 或 WebP，每张不超过 10 MB，私有存储在您的账号中。申请审核前需至少上传一张。",
    remove: "移除",
    photoError: "请选择最多 8 张 JPG、PNG 或 WebP 图片，每张不超过 10 MB。",
    photoPreviewError: "有照片暂时无法显示。请检查网络，并重新载入项目以更新预览。",
    next: "下一步",
    previous: "上一步",
    appointmentTitle: "留下您的联系方式。",
    appointmentText:
      "填写联系方式，也可以选填方便沟通的日期。日期只是您的意向，并不代表预约已经确认。",
    name: "姓名",
    email: "电子邮箱",
    phone: "联系电话",
    date: "期望日期（选填）",
    noAppointment: "暂未填写沟通日期，也未安排预约",
    time: "方便时段",
    times: ["上午", "下午", "晚上"],
    language: "沟通语言",
    notes: "补充说明（选填）",
    consent: "我同意将资料保存在自己的私有账号中，并允许授权团队为处理此项目查看资料。审核不会自动公开资料，也不会确认任何服务。",
    review: "核对我的信息",
    reviewTitle: "核对信息，准备下一步。",
    reviewText: "请核对所选方案、房屋资料及联系方式，再保存并进入卖家工作台。",
    service: "所选方案",
    property: "房屋资料",
    appointment: "期望预约时间",
    contact: "联系方式",
    included: "与经纪另行约定的服务",
    estimate: "参考费用",
    noCharge: "不会扣取任何费用。实际付款前，需要另行确认最终价格和税费。",
    finish: "保存我的项目",
    doneTitle: "您的卖房流程已准备好。",
    doneText:
      "项目已保存在您的私有账号中。尚未购买任何服务、确认预约，也没有产生付款。",
    again: "返回首页",
    edit: "修改",
    photosCount: "张已保存照片",
    required: "带 * 的项目为必填。",
    invalidDate: "请选择今天或之后的日期。",
    invalidPrice: "请输入大于零的金额。",
    invalidPostal: "请输入有效的加拿大邮编。",
  },
};
export type Language = keyof typeof sellerCopy;
