export const sellerCopy = {
  fr: {
    back: "Retour à l’accueil",
    eyebrow: "VENDRE À VOTRE FAÇON",
    title: "Votre propriété. Votre façon de vendre.",
    intro:
      "À Montréal, avancez à votre rythme : vendez vous-même et ajoutez de l’aide au besoin, ou choisissez un courtier.",
    steps: [
      "Votre formule",
      "Votre propriété",
      "Votre rendez-vous",
      "Récapitulatif",
    ],
    with: "Avec courtier",
    without: "Sans courtier",
    withTag: "Un professionnel à vos côtés",
    withoutTag: "Vous gardez les commandes",
    withText: "Un courtier vous accompagne de l’évaluation à la signature.",
    withoutText:
      "Vous gérez votre vente et choisissez progressivement les services dont vous avez besoin.",
    withItems: [
      "Évaluation comparative par un courtier",
      "Photographie et mise en marché",
      "Coordination des visites et des offres",
      "Négociation et suivi de la transaction",
    ],
    withoutItems: [
      "Séance photo professionnelle",
      "Vidéo de présentation de la propriété",
      "Analyse de marché par un professionnel qualifié",
      "Conception de la fiche et préparation des informations",
    ],
    agreed: "Honoraires selon le mandat",
    agreedNote:
      "Les services et la commission sont convenus avec votre courtier avant tout engagement.",
    sample: "Prix d’exemple",
    taxes: "CAD + taxes",
    fixed: "Services à la carte • sans achat à cette étape",
    chooseWith: "Choisir un courtier",
    chooseWithout: "Choisir la vente autonome",
    boundary:
      "Le forfait sans courtier ne comprend pas la représentation, les visites ni la négociation. Toute assistance de courtage ferait l’objet d’un accord distinct.",
    demo: "Version de démonstration : aucun paiement, envoi de données ou rendez-vous confirmé.",
    propertyTitle: "Parlons de votre propriété.",
    propertyText:
      "Ces informations serviront à préparer une évaluation ou une séance photo.",
    address: "Adresse de la propriété",
    city: "Ville",
    postal: "Code postal",
    type: "Type de propriété",
    price: "Prix souhaité (CAD, facultatif)",
    types: ["Maison", "Condo", "Plex", "Commercial"],
    broker: "Avez-vous déjà un courtier ?",
    brokerOptions: ["Non", "Oui", "Je préfère en discuter"],
    timeline: "Quand souhaitez-vous vendre ?",
    timelines: [
      "Dès que possible",
      "Dans 1 à 3 mois",
      "Dans 3 à 6 mois",
      "Je me renseigne",
    ],
    photos: "Photos de votre propriété (facultatif)",
    photoHelp:
      "Jusqu’à 8 fichiers JPG, PNG ou WebP, 10 Mo chacun. Aperçu local uniquement.",
    remove: "Retirer",
    photoError:
      "Choisissez jusqu’à 8 images JPG, PNG ou WebP de 10 Mo maximum chacune.",
    next: "Continuer",
    previous: "Retour",
    appointmentTitle: "Préparons un premier rendez-vous.",
    appointmentText:
      "Indiquez vos coordonnées et une disponibilité souhaitée. Il s’agit d’une préférence, pas d’une réservation.",
    name: "Nom complet",
    email: "Courriel",
    phone: "Téléphone",
    date: "Date souhaitée",
    time: "Moment préféré",
    times: ["Matin", "Après-midi", "Soir"],
    language: "Langue de communication",
    notes: "Précisions (facultatif)",
    consent:
      "Je comprends que cette démonstration ne transmet pas mes informations et ne confirme aucun service.",
    review: "Vérifier mes informations",
    reviewTitle: "Tout est prêt pour la prochaine étape.",
    reviewText:
      "Vérifiez votre parcours et vos préférences avant de terminer cette démonstration.",
    service: "Votre formule",
    property: "Votre propriété",
    appointment: "Votre disponibilité souhaitée",
    contact: "Vos coordonnées",
    included: "Inclus dans votre formule",
    estimate: "Tarif indicatif",
    noCharge:
      "Aucun montant ne sera débité. Le prix final et les taxes devront être confirmés avant un véritable paiement.",
    finish: "Terminer la démonstration",
    doneTitle: "Votre parcours est prêt.",
    doneText:
      "Vous avez terminé la démonstration. Vos informations n’ont pas été envoyées, votre rendez-vous n’est pas réservé et aucun paiement n’a été effectué.",
    again: "Revenir à l’accueil",
    edit: "Modifier",
    photosCount: "photo(s) sélectionnée(s)",
    required: "Les champs marqués * sont obligatoires.",
    invalidDate: "Choisissez une date à partir d’aujourd’hui.",
    invalidPrice: "Indiquez un montant positif.",
    invalidPostal: "Saisissez un code postal canadien valide.",
  },
  en: {
    back: "Back to home",
    eyebrow: "SELL YOUR WAY",
    title: "Your property. Your way to sell.",
    intro:
      "In Montréal, sell at your own pace: start independently and add help as you need it, or choose a broker.",
    steps: ["Your service", "Your property", "Your appointment", "Review"],
    with: "With a broker",
    without: "Without a broker",
    withTag: "A professional by your side",
    withoutTag: "You stay in control",
    withText: "A broker supports you from valuation through signing.",
    withoutText:
      "Manage your sale and add professional help whenever you need it.",
    withItems: [
      "Comparative valuation by a broker",
      "Photography and marketing",
      "Visit and offer coordination",
      "Negotiation and transaction follow-up",
    ],
    withoutItems: [
      "Professional photography session",
      "Property presentation video",
      "Market analysis by a qualified professional",
      "Listing page design and information preparation",
    ],
    agreed: "Fees agreed in the mandate",
    agreedNote:
      "Services and commission are agreed with your broker before any commitment.",
    sample: "Example price",
    taxes: "CAD + taxes",
    fixed: "Optional services • no purchase at this step",
    chooseWith: "Choose broker support",
    chooseWithout: "Choose self-sale",
    boundary:
      "The self-sale package excludes representation, visits and negotiation. Any brokerage assistance would require a separate agreement.",
    demo: "Demo version: no payment, data submission or confirmed appointment.",
    propertyTitle: "Tell us about your property.",
    propertyText:
      "These details help prepare a valuation or photography session.",
    address: "Property address",
    city: "City",
    postal: "Postal code",
    type: "Property type",
    price: "Desired price (CAD, optional)",
    types: ["House", "Condo", "Plex", "Commercial"],
    broker: "Do you already have a broker?",
    brokerOptions: ["No", "Yes", "I would like to discuss it"],
    timeline: "When would you like to sell?",
    timelines: [
      "As soon as possible",
      "In 1–3 months",
      "In 3–6 months",
      "Just exploring",
    ],
    photos: "Property photos (optional)",
    photoHelp:
      "Up to 8 JPG, PNG or WebP files, 10 MB each. Local previews only.",
    remove: "Remove",
    photoError:
      "Choose up to 8 JPG, PNG or WebP images, no larger than 10 MB each.",
    next: "Continue",
    previous: "Back",
    appointmentTitle: "Plan a first appointment.",
    appointmentText:
      "Enter your contact details and preferred availability. This is a preference, not a booking.",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    date: "Preferred date",
    time: "Preferred time",
    times: ["Morning", "Afternoon", "Evening"],
    language: "Communication language",
    notes: "Additional details (optional)",
    consent:
      "I understand that this demo does not transmit my information or confirm any service.",
    review: "Review my information",
    reviewTitle: "Ready for the next step.",
    reviewText:
      "Review your chosen service and preferences before completing this demo.",
    service: "Your service",
    property: "Your property",
    appointment: "Your preferred availability",
    contact: "Your contact details",
    included: "Included in your service",
    estimate: "Indicative price",
    noCharge:
      "Nothing will be charged. The final price and taxes must be confirmed before an actual payment.",
    finish: "Complete the demo",
    doneTitle: "Your plan is ready.",
    doneText:
      "You have completed the demo. Your information has not been sent, your appointment is not booked and no payment has been taken.",
    again: "Back to home",
    edit: "Edit",
    photosCount: "photo(s) selected",
    required: "Fields marked * are required.",
    invalidDate: "Choose today or a future date.",
    invalidPrice: "Enter a positive amount.",
    invalidPostal: "Enter a valid Canadian postal code.",
  },
  zh: {
    back: "返回首页",
    eyebrow: "选择适合您的卖房方式",
    title: "您的房产，由您选择怎样出售。",
    intro:
      "服务蒙特利尔：先自主卖房，再按需要增加专业帮助；也可以选择经纪全程协助。",
    steps: ["选择方案", "房屋资料", "预约意向", "核对信息"],
    with: "有经纪服务",
    without: "无经纪自售",
    withTag: "专业经纪全程协助",
    withoutTag: "卖房节奏由您掌握",
    withText: "从房产评估到签字完成，由经纪陪您处理每个环节。",
    withoutText: "先自主推进卖房，再按需要选择摄影、视频、市场分析或咨询。",
    withItems: [
      "经纪提供同类房产对比评估",
      "专业摄影与上市推广",
      "协调看房和管理报价",
      "谈判协助与交易跟进",
    ],
    withoutItems: [
      "专业人员上门拍摄房屋照片",
      "房屋展示视频",
      "由合资格专业人士提供市场分析",
      "房源页面设计与资料整理",
    ],
    agreed: "费用按经纪协议确定",
    agreedNote: "签约前与经纪确认服务范围及佣金，不在此页面收取费用。",
    sample: "示例价格",
    taxes: "加元 + 税",
    fixed: "按需选择服务 · 此步骤无需购买",
    chooseWith: "选择经纪服务",
    chooseWithout: "选择自主出售",
    boundary:
      "自售套餐不包含经纪代理、带看或谈判。若需经纪协助，须另行确认服务及协议。",
    demo: "当前为演示版：不会扣款、发送个人资料或确认预约。",
    propertyTitle: "先了解一下您的房屋。",
    propertyText: "这些信息用于准备房产评估或上门拍摄。",
    address: "房屋地址",
    city: "城市",
    postal: "邮政编码",
    type: "房产类型",
    price: "期望售价（加元，选填）",
    types: ["独立屋 / House", "公寓 / Condo", "多户住宅 / Plex", "商业物业"],
    broker: "您目前是否已有经纪？",
    brokerOptions: ["没有", "有", "希望进一步沟通"],
    timeline: "希望什么时候出售？",
    timelines: ["尽快出售", "1–3 个月内", "3–6 个月内", "先了解一下"],
    photos: "房屋照片（选填）",
    photoHelp: "最多 8 张 JPG、PNG 或 WebP，每张不超过 10 MB。仅在本机预览。",
    remove: "移除",
    photoError: "请选择最多 8 张 JPG、PNG 或 WebP 图片，每张不超过 10 MB。",
    next: "下一步",
    previous: "上一步",
    appointmentTitle: "安排一次初步沟通。",
    appointmentText:
      "填写联系方式和方便的时间。这里只记录预约意向，并不代表预约已经确认。",
    name: "姓名",
    email: "电子邮箱",
    phone: "联系电话",
    date: "期望日期",
    time: "方便时段",
    times: ["上午", "下午", "晚上"],
    language: "沟通语言",
    notes: "补充说明（选填）",
    consent: "我了解这是演示流程，不会发送我的资料或确认任何服务。",
    review: "核对我的信息",
    reviewTitle: "核对信息，准备下一步。",
    reviewText: "请检查所选方案、房屋资料及预约意向，再完成本次演示。",
    service: "所选方案",
    property: "房屋资料",
    appointment: "期望预约时间",
    contact: "联系方式",
    included: "方案包含",
    estimate: "参考费用",
    noCharge: "不会扣取任何费用。实际付款前，需要另行确认最终价格和税费。",
    finish: "完成演示",
    doneTitle: "您的卖房流程已准备好。",
    doneText:
      "本次演示已完成。您的资料没有发送，预约尚未确认，也没有产生任何付款。",
    again: "返回首页",
    edit: "修改",
    photosCount: "张已选照片",
    required: "带 * 的项目为必填。",
    invalidDate: "请选择今天或之后的日期。",
    invalidPrice: "请输入大于零的金额。",
    invalidPostal: "请输入有效的加拿大邮编。",
  },
};
export type Language = keyof typeof sellerCopy;
